version: '3.1'

services:
  postgres:
    image: postgres:14-alpine
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 60s
      retries: 5
