version: '3.1'

services:
  postgres:
    image: postgres:14-alpine
    restart: "no"
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 60s
      retries: 5
  rust-url-shortener:
    build:
      context: .
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      SERVER: 0.0.0.0:8080
      DATABASE_URL: "postgresql://postgres:mysecretpassword@postgres:5432/postgres"
      RUST_LOG: "Debug"
    ports:
      - "8081:8080"
